import type { Metadata } from "next";
import "./globals.css";
import { AppSetting } from "../data/appSetting";
import { BaseTemplate } from "../data/templates/base";

export const metadata: Metadata = {
  title: `${AppSetting.appName} - ${BaseTemplate.fullName} Portfolio`,
  description: `Generated by ${AppSetting.appName}`,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
